baseURL = "hugo.io/Translation_Norms/"
languageCode = "zh-CN"

title = "翻译说明"
defaultContentLanguage  = "cn"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
  sidebarColor = "quic"
  customCss = ["css/Translation_Norms.css"]

[[menu.shortcuts]]
  name = "RFC8999 QUIC版本通用属性"
  weight = 10
  [menu.shortcuts.Params]
    lateralurl = "/RFC8999_Chinese_Translation/"


[[menu.shortcuts]]
  name = "RFC9000 QUIC传输协议"
  weight = 10
  [menu.shortcuts.Params]
    lateralurl = "/RFC9000_Chinese_Translation/"

[markup]
  #defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true